/*
api/api.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package httpclient

import (
	"encoding/json"
)

// checks if the ApiPutThingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiPutThingResponse{}

// ApiPutThingResponse struct for ApiPutThingResponse
type ApiPutThingResponse struct {
	Thing *ModelThing `json:"thing,omitempty"`
}

// NewApiPutThingResponse instantiates a new ApiPutThingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiPutThingResponse() *ApiPutThingResponse {
	this := ApiPutThingResponse{}
	return &this
}

// NewApiPutThingResponseWithDefaults instantiates a new ApiPutThingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiPutThingResponseWithDefaults() *ApiPutThingResponse {
	this := ApiPutThingResponse{}
	return &this
}

// GetThing returns the Thing field value if set, zero value otherwise.
func (o *ApiPutThingResponse) GetThing() ModelThing {
	if o == nil || IsNil(o.Thing) {
		var ret ModelThing
		return ret
	}
	return *o.Thing
}

// GetThingOk returns a tuple with the Thing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPutThingResponse) GetThingOk() (*ModelThing, bool) {
	if o == nil || IsNil(o.Thing) {
		return nil, false
	}
	return o.Thing, true
}

// HasThing returns a boolean if a field has been set.
func (o *ApiPutThingResponse) HasThing() bool {
	if o != nil && !IsNil(o.Thing) {
		return true
	}

	return false
}

// SetThing gets a reference to the given ModelThing and assigns it to the Thing field.
func (o *ApiPutThingResponse) SetThing(v ModelThing) {
	o.Thing = &v
}

func (o ApiPutThingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiPutThingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Thing) {
		toSerialize["thing"] = o.Thing
	}
	return toSerialize, nil
}

type NullableApiPutThingResponse struct {
	value *ApiPutThingResponse
	isSet bool
}

func (v NullableApiPutThingResponse) Get() *ApiPutThingResponse {
	return v.value
}

func (v *NullableApiPutThingResponse) Set(val *ApiPutThingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiPutThingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiPutThingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiPutThingResponse(val *ApiPutThingResponse) *NullableApiPutThingResponse {
	return &NullableApiPutThingResponse{value: val, isSet: true}
}

func (v NullableApiPutThingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiPutThingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


