/*
api/api.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package httpclient

import (
	"encoding/json"
)

// checks if the ApiGetThingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiGetThingResponse{}

// ApiGetThingResponse struct for ApiGetThingResponse
type ApiGetThingResponse struct {
	Thing *ModelThing `json:"thing,omitempty"`
}

// NewApiGetThingResponse instantiates a new ApiGetThingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiGetThingResponse() *ApiGetThingResponse {
	this := ApiGetThingResponse{}
	return &this
}

// NewApiGetThingResponseWithDefaults instantiates a new ApiGetThingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiGetThingResponseWithDefaults() *ApiGetThingResponse {
	this := ApiGetThingResponse{}
	return &this
}

// GetThing returns the Thing field value if set, zero value otherwise.
func (o *ApiGetThingResponse) GetThing() ModelThing {
	if o == nil || IsNil(o.Thing) {
		var ret ModelThing
		return ret
	}
	return *o.Thing
}

// GetThingOk returns a tuple with the Thing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetThingResponse) GetThingOk() (*ModelThing, bool) {
	if o == nil || IsNil(o.Thing) {
		return nil, false
	}
	return o.Thing, true
}

// HasThing returns a boolean if a field has been set.
func (o *ApiGetThingResponse) HasThing() bool {
	if o != nil && !IsNil(o.Thing) {
		return true
	}

	return false
}

// SetThing gets a reference to the given ModelThing and assigns it to the Thing field.
func (o *ApiGetThingResponse) SetThing(v ModelThing) {
	o.Thing = &v
}

func (o ApiGetThingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiGetThingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Thing) {
		toSerialize["thing"] = o.Thing
	}
	return toSerialize, nil
}

type NullableApiGetThingResponse struct {
	value *ApiGetThingResponse
	isSet bool
}

func (v NullableApiGetThingResponse) Get() *ApiGetThingResponse {
	return v.value
}

func (v *NullableApiGetThingResponse) Set(val *ApiGetThingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiGetThingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiGetThingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiGetThingResponse(val *ApiGetThingResponse) *NullableApiGetThingResponse {
	return &NullableApiGetThingResponse{value: val, isSet: true}
}

func (v NullableApiGetThingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiGetThingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


